version: "3.1"

services:
  db:
    container_name: mongoDB
    image: mongo:3.6
    restart: always
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE= Pokemon
    ports:
      - 27018:27017

  app:
    container_name: pokeAPIServer
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 9001:9001

volumes:
  db-data:
